import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = process.cwd();
const sourceSchema = join(root, "prisma", "schema.prisma");
const outputDir = join(root, ".prisma-cloud");
const outputSchema = join(outputDir, "schema.prisma");
const requestedProvider = process.env.DATABASE_PROVIDER || "postgres";
const databaseUrl = process.env.DATABASE_URL || "";

function normalizeProvider(value: string) {
  return value === "postgresql" ? "postgres" : value;
}

const provider = normalizeProvider(requestedProvider);

if (provider !== "postgres") {
  console.warn(`[prepare-cloud-prisma] DATABASE_PROVIDER=${requestedProvider}. Cloud schema will still use PostgreSQL.`);
}

if (databaseUrl && !databaseUrl.startsWith("postgresql://") && !databaseUrl.startsWith("postgres://")) {
  console.warn("[prepare-cloud-prisma] DATABASE_URL does not look like a PostgreSQL URL. Vercel cloud deploy should use Neon/Supabase/Railway Postgres.");
}

const schema = readFileSync(sourceSchema, "utf8");
const cloudSchema = schema.replace(/provider\s*=\s*"sqlite"/, 'provider = "postgresql"');

if (cloudSchema === schema) {
  throw new Error("Could not replace Prisma datasource provider. Expected provider = \"sqlite\" in prisma/schema.prisma.");
}

if (!existsSync(outputDir)) {
  mkdirSync(outputDir, { recursive: true });
}

writeFileSync(
  outputSchema,
  [
    "// Generated by scripts/prepare-cloud-prisma.ts.",
    "// Do not edit this file directly. Edit prisma/schema.prisma instead.",
    cloudSchema
  ].join("\n"),
  "utf8"
);

console.log(`[prepare-cloud-prisma] Wrote PostgreSQL schema to ${outputSchema}`);
